### ISSUE TITLE
Crash after changing metro.config.js - > node_modules\expo-router\entry.js: traverse is not a function

### ISSUE THREAD

**Issue by katche70** [inokawa/react-native-react-bridge#126]
**Describe the bug**
after changing metro.config.js to 
module.exports = {
  ...config,
  transformer: {
    ...config.transformer,
    babelTransformerPath: require.resolve(
      "react-native-react-bridge/lib/plugin"
    ),
  },
};
i can't start react app anymore:
 node_modules\expo-router\entry.js: traverse is not a function

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Platform:**
 - OS: iOS, Android, wen
 - Running on: Device, Browser
 - Version of this package: ^0.11.0

**Additional context**
Web Bundling failed 826ms
error: node_modules\expo-router\_error.js: traverse is not a function
Web node_modules\expo-router/entry.js ░░░░░░░░░░░░░░░░  0.0% (0/1)
Metro error: node_modules\expo-router\entry.js: traverse is not a function

Call Stack
  MetroBundlerDevServer.getStaticResourcesAsync (node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js)
  process.processTicksAndRejections (node:internal/process/task_queues)
  async MetroBundlerDevServer.getStaticPageAsync (node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js)
  async (node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js)
Web Bundling failed 10ms
error: node_modules\expo-router\entry.js: traverse is not a function
Web Bundling failed 9ms
error: node_modules\expo-router\node\render.js: traverse is not a function
Web Bundling failed 12ms
error: node_modules\expo-router\_error.js: traverse is not a function
› Detected a change in babel.config.js. Restart the server to see the new results. You may need to clear the bundler cache with the --clear flag for your changes to take effect.

**Comment by iabdulhannan** [comment]
Facing the same issue!

**Comment by inokawa** [comment]
Thanks!
I've released a patch `0.11.1`. Could you try it?

**Comment by iabdulhannan** [comment]
Hey! The patch `0.11.1` worked, the error is gone but now I'm facing the following:

`ReferenceError: Property 'n' doesn't exist, js engine: hermes`.

To reproduce it, just create an Expo project and follow the instructions on this package's Homepage to create a demo project.

**Comment by accelerate-dm** [comment]
> Hey! The patch `0.11.1` worked, the error is gone but now I'm facing the following:
> 
> `ReferenceError: Property 'n' doesn't exist, js engine: hermes`.
> 
> To reproduce it, just create an Expo project and follow the instructions on this package's Homepage to create a demo project.

Are you suggesting we use the new_script function as is but instead of using a path we copy the whole code block in myAlert.js inside the double quotes? Or should we not use the new_script function at all and refer to our code in a different way? We're struggling to understand how we should reference the code block. This is our standalone setup that runs by itself in html/js that we are trying to run inside the react component using react-native-react-bridge: https://gist.github.com/zserge/6617cdbf328aac76913ff9ae85350c10

**Comment by accelerate-dm** [comment]
<img width="476" alt="Screenshot 2023-09-14 at 5 53 15 PM" src="https://github.com/inokawa/react-native-react-bridge/assets/103406117/2983e83c-fdb6-43b0-a755-ea96520a704f">

 I am also facing same issue with version 0.11.1.

**Comment by edjiang** [comment]
Having the same issue. Any ideas?

**Comment by inokawa** [comment]
`0.11.2` is released. Thanks!
