### ISSUE TITLE
Expecting Unicode escape sequence \uXXXX

### ISSUE THREAD

**Issue by farwayer** [inokawa/react-native-react-bridge#144]
**Describe the bug** 

Transformation failed in some cases with the error
```js
 [Error: TransformError SyntaxError: Expecting Unicode escape sequence \uXXXX
```

**To Reproduce**
```js
import {webViewRender} from 'react-native-react-bridge/lib/web'

let Root = () => {
  let issue = function inspect(value) {
    switch (typeof value) {
      case 'string':
        if (value.includes("'")) {
          if (!value.includes('"')) {
            return `"${value}"`;
          } else if (!value.includes('`') && !value.includes('${')) {
            return `\`${value}\``;
          }
        }
    }
  };
  console.log(issue)

  return null
}

export default webViewRender(<Root/>)
```

**Platform:**

 - Version of react-native: 0.72.7
 - Version of this package: 0.11.2

**Additional context**

Look like the issue is inside `createContent()` while processing react bundle

**Comment by farwayer** [comment]
![2023_11_19T21 57 18](https://github.com/inokawa/react-native-react-bridge/assets/2343101/d9805300-5881-4836-8afb-da20a81a5702)

**Comment by theprashant-one** [comment]
Getting the same error when updated to expo 49

**Comment by ieow** [comment]
try add resolve in metro.config.js file
```
const config =  {
    resolver: {
      extraNodeModules: {
        stream: require.resolve('stream-browserify'),
```

**Comment by farwayer** [comment]
@theprashant-one just added the hack to remove sequence that causes the problem

```js
diff --git a/lib/plugin/index.js b/lib/plugin/index.js
const createContent = (js) => {
+  js = js.replace('return`\\`${t}\\``', 'return')
   js = js.replace(/([`$])/g, '\\$1');
   return "export default String.raw`\n"+wrapByHtml(js)+"\n`.replace(/\\\\([`$])/g, '\\$1')"; 
 };
```

**Comment by theprashant-one** [comment]
> @theprashant-one just added the hack to remove the sequence that causes the problem in my case
> 
> ```js
> diff --git a/lib/plugin/index.js b/lib/plugin/index.js
> const createContent = (js) => {
> +  js = js.replace('return`\\`${t}\\``', 'return')
>    js = js.replace(/([`$])/g, '\\$1');
>    return "export default String.raw`\n"+wrapByHtml(js)+"\n`.replace(/\\\\([`$])/g, '\\$1')"; 
>  };
> ```

Thanks for the response. I got it working from removing that particular code

**Comment by farwayer** [comment]
Unfortunately, the issue is still reproducible. IMO it's not related to babel/esbuild code build, but to escaping `` ` `` character in regexp for `replace`:
```js
const createTransformer = (esbuildOptions = {}) => {
    return async (args /* TODO */) => {
        const { filename, src } = args;
        const isEntry = isEntryFile(src, filename);
        if (isEntry) {
            const res = await bundle(filename, metroOptions, esbuildOptions);
            return metroTransformer.transform({
                ...args,
                src: "export default String.raw`" +
                    escape(res).replace(/\$/g, '\\$') +
                    "`.replace(/\\\\([`$])/g, '\\$1')",
            });
        }
        return metroTransformer.transform(args);
    };
};
```
similar issues #182 #198
