### ISSUE TITLE
Demo App not working for EXPO 50 sdk

### ISSUE THREAD

**Issue by theprashant-one** [inokawa/react-native-react-bridge#158]
**Describe the bug**
no elements showing on the screen (maybe error has happened inside the webview on running)

**To Reproduce**
- upgrade the app to expo 50 sdk
- add metro-react-native-babel-transformer (or patch with @react-native/metro-babel-transformer inside plugin/index.js and transformer.js)
- bundle the app
- run it

![bug](https://github.com/inokawa/react-native-react-bridge/assets/26407503/f3cb28fd-9d33-4fad-a1b3-4d4b9549e070)

**Expected behavior**
Should work as expected

**Platform:**
 - Version of react-native: [0.73.2]
 - Version of this package: [0.11.2]
 - Version of expo (only if you use it): [50.0.2]
 - OS: [Android]
 - Running on: [Device,]
 - JavaScript engine: [Hermes]

**Comment by theprashant-one** [comment]
@inokawa Did you have any idea on it?

**Comment by inokawa** [comment]
Probably similar issue to #153

**Comment by chef-jojo** [comment]
If using expo replace with `@expo/metro-config/babel-transformer` should work.

Can we have a separate plugin entry file for react native and expo?

**Comment by inokawa** [comment]
It's fine. Any contribution is welcome.
