### ISSUE TITLE
Xcode fails to build after following setup instructions

### ISSUE THREAD

**Issue by asharafshahi** [inokawa/react-native-react-bridge#18]
Any idea why this error would be thrown by Xcode?

`Error: Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. src/web/sketch/index.js: src/web/sketch/index.js: Import statement may only appear at top level in file src/web/sketch/index.js at 4:2`

**Comment by inokawa** [comment]
Hi, @asharafshahi,
I guess it may not be a issue about this lib but a ESLint error.
Could you check where you put your import statements, or could you show me more detailed logs?

**Comment by asharafshahi** [comment]
Thanks @inokawa.  I was able to get the project to build after i changed babel.config.js from:
`presets: ['babel-preset-expo'],` to `presets: ['module:metro-react-native-babel-preset'],`
