### ISSUE TITLE
Question about CSS files

### ISSUE THREAD

**Issue by asharafshahi** [inokawa/react-native-react-bridge#19]
Hi @inokawa - This is a really neat project and I'm surprised there isn't more out there to handle this use case!  One question I have for you is how to handle the case where the web components have CSS files?  

Xcode fails during the build process because I think the bundler doesn't see the CSS files: 
```
: Unable to resolve module `./css/Sketch.css` from `src/web/sketch/components/Sketch.js`: 

None of these files exist:
  * src/web/sketch/components/css/Sketch.css(.native|.web.js|.native.js|.js|.web.ts|.native.ts|.ts|.web.jsx|.native.jsx|.jsx|.web.tsx|.native.tsx|.tsx)
  * src/web/sketch/components/css/Sketch.css/index(.native|.web.js|.native.js|.js|.web.ts|.native.ts|.ts|.web.jsx|.native.jsx|.jsx|.web.tsx|.native.tsx|.tsx)
    at /Users/asharafshahi/Projects/UpWork/trueprodigy/prodigy-mobile/realm-test/mobileAppUI/node_modules/expo-updates/scripts/createManifest.js:27:11
```

Is there a way to get it to look for css files as well?  thanks

**Comment by inokawa** [comment]
Hi,
as the log shows, this lib doesn't handle `.css` extension currently .
However it's logically possible to detect importing of css and inject them to the WebView html.
So I'll try to implement it soon. Thank you.

**Comment by inokawa** [comment]
@asharafshahi 
```javascript
import "foo/bar.css";
```
syntax is supported in `0.2.0`. Thanks!
