### ISSUE TITLE
Preact support

### ISSUE THREAD

**Issue by jasonnathan** [inokawa/react-native-react-bridge#27]
Hi, thanks for the great library. Curious how I might support [Preact](https://preactjs.com/) instead of React. I'd need to alias it somewhere, just not sure where exactly

**Comment by inokawa** [comment]
Hi, you intended to run preact web app in react native, right?

Internally, this lib depends on render from `react-dom` and hooks from `react`.
So I think it's possible but I don't know how to alias them in build process of metro bundler. If metro didn't have the way to alias them, it's needed to make plugin for preact like react.

**Comment by inokawa** [comment]
Finally, I added support for Preact in 0.5.0.
Thank you for your nice suggestion!
