### ISSUE TITLE
Can't add to existing RN project using Hermes engine

### ISSUE THREAD

**Issue by lucijafrkovic** [inokawa/react-native-react-bridge#44]
I'm trying to use react-native-react-bridge in an existing project to avoid messaging issues in WebView between my React app and RN.

I've followed the docs (added metro config, imported the proper imports etc) and got it working in an example project, but can't seem to work it out for an existing project.

I have a RN component referencing a React component in WebView (using source html tag), but my app keeps breaking when my RN component is loaded, saying 

ReferenceError: Property \'document\' doesn\'t exist, js engine: hermes', '\n    at _default (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=my.bundle.id.

I'd really like to get this to work, but have no idea how to debug this.

**Comment by inokawa** [comment]
This lib hasn't tested with Hermes yet.
And I guess this lib doesn't work with Hermes, because of Hermes' bytecode precompilation.

I need to do some investigation to judge it is fixable or not.

**Comment by clayrisser** [comment]
@lucijafrkovic @inokawa how would I disabled hermes?

**Comment by inokawa** [comment]
It looks like that this lib works fine on hermes engine, at least `react-native: 0.66.3` with `react-native-react-bridge: 0.8.1`.
I updated demo to this versions, so you can [try it](https://github.com/inokawa/react-native-react-bridge/tree/main/examples/DemoApp) if you [enables hermes](https://reactnative.dev/docs/hermes).
