### ISSUE TITLE
Backtick ` causes packaging error

### ISSUE THREAD

**Issue by mgarabedian** [inokawa/react-native-react-bridge#45]
The react package I am trying to import into the webview contains backticks, and the bundler plugin fails on that.

(This package is very useful, thank you!)

**Comment by inokawa** [comment]
@mgarabedian 
Could give me the information about the lib you used or the detailed error log?
Thank you for your reporting.

**Comment by mgarabedian** [comment]
I was attempting to use TipTap in a Webview ( https://www.tiptap.dev/installation ), and was having the issues.

**Comment by inokawa** [comment]
Fixed in `0.8.0`. Thanks!
