### ISSUE TITLE
Feature Request: Add option to customize sourceExts

### ISSUE THREAD

**Issue by mgarabedian** [inokawa/react-native-react-bridge#46]
One of the packages I am using utilizes a 'cjs' file type. I made the update for react native in metro.config.js, in resolver -> sourceExts. However, it looks like the plugin bundles via hardcoded codeExts. It would be nice to be able to customize these, or somehow import from the metro config file.

**Comment by inokawa** [comment]
I added `cjs` to the hardcorded exts in `0.7.3`.

Configurable sourceExts sounds nice but currently this lib needs customized logic for each exts so it may not be worth the cost.

**Comment by mgarabedian** [comment]
Thanks, understandable. Currently I am running a forked version that hardcodes the config I required, including the resolver blacklist ( blacklistRE ). Blacklisting is required for my setup, and am copying that code from metro.config.js in the plugin.

**Comment by inokawa** [comment]
prefer #178
