### ISSUE TITLE
Importing HighCharts More module inside the WebApp makes webview blank

### ISSUE THREAD

**Issue by JairajJangleSLIOT** [inokawa/react-native-react-bridge#52]
How the import statements look:
```
.
.
.
import Highcharts from "highcharts";
import highchartsMore from 'highcharts/highcharts-more';

/////////////////////////// Problematic imports /////////////////////////////////////
import solidGauge from 'highcharts/modules/solid-gauge.js';
import HighchartsReact from "highcharts-react-official";

highchartsMore(Highcharts);
solidGauge(Highcharts);
/////////////////////////////////////////////////////////////////////////////////////

const Root = () => {
.
.
.
}

export default webViewRender(<Root />);
```

version of Highcharts package in my package json
```
"highcharts": "^8.0.4",
"highcharts-react-official": "^3.0.0",
```

When I remove the "Problematic imports" webview displays the react app as expected.

Running the same code in plain react app on localhost works totally fine.

Can anyone shed light on why importing those libraries causes the webview to just go blank?

**Comment by inokawa** [comment]
@JairajJangleSLIOT 
Could you give me information about what the error says?
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onerror
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#rendererror

**Comment by JairajJangleSLIOT** [comment]
Thanks, @inokawa for the follow-up, found out that this issue is a HighCharts-only issue.
