### ISSUE TITLE
Unable to resolve module fabricjs-react

### ISSUE THREAD

**Issue by Shasikhan** [inokawa/react-native-react-bridge#69]
I installed fabric js lib in the provided example and this is giving following error. 

error: WebApp/index.js: Unable to resolve module fabricjs-react from ...myProject/WebApp/index.js: fabricjs-react could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  12 | // import DesignCanvas from "./DesignCanvas";
  13 | import Rect from "./Rect";
> 14 | import { FabricJSCanvas, useFabricJSEditor } from "fabricjs-react";
     |                                                    ^
  15 | const style = {
  16 |   width: "100vw",
  17 |   height: "100vh",

I checked fabric js js installed and is in node_modules folder. 
----Please help.

**Comment by inokawa** [comment]
Hi.
At first, thank you for using my library.

[Looking at the fabricjs-react's install guide](https://github.com/asotog/fabricjs-react#install), `fabricjs-react fabric react react-dom` are the required dependencies.
Are all of these in your node_modules dir?

Thanks.

**Comment by Shasikhan** [comment]
Thanks for your reply.
Yes I installed all required libs and all are in my projects node_modules

**Comment by inokawa** [comment]
After some investigation, it looks like that import statement in WebView side does not work correctly in the newest react-native.

If you need to complete your program asap, you may have to downgrade your react-native.
This library would work with `react-native 0.63.4`, it is the version currently used in development of this lib.

I'll try to fix it. Thank you for your reporting.

**Comment by Shasikhan** [comment]
Thank you so much, Let me try this and then inform you

**Comment by inokawa** [comment]
Probably fixed in `0.9.0`.
Thanks!
