### ISSUE TITLE
Can't find variable: document

### ISSUE THREAD

**Issue by josefdclxvi** [inokawa/react-native-react-bridge#76]
hi,

running reactjs to react native is awesome, but when i tried to install this, its not working on me.

i just did your example and found this bug

- ReferenceError: Can't find variable: document

i would appreciate your help, thanks

![Screenshot_135](https://user-images.githubusercontent.com/45645153/153884977-697b83a9-ca97-4f51-8601-67ef7d5db8e3.png)
s

**Comment by inokawa** [comment]
Hi, do you have more detailed logs?

**Comment by josefdclxvi** [comment]
hi inokawa,

my mistake, im so sorry.

the problem is this, i put it in the wrong place
![image](https://user-images.githubusercontent.com/45645153/153972549-275a7a44-eb85-46e7-ad5b-9eb1989a0d9b.png)

which is, should be like this
![image](https://user-images.githubusercontent.com/45645153/153972640-f7740520-fc43-4fe6-8fd4-9cd212ebaefb.png)

its now working great. thank you so much
